// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "devmetrics/controllers/application"

import HelloController from "devmetrics/controllers/hello_controller"
application.register("hello", HelloController)

import MetricsController from "devmetrics/controllers/metrics_controller"
application.register("metrics", MetricsController)

import PlaygroundController from "devmetrics/controllers/playground_controller"
application.register("playground", PlaygroundController)
